version: '3.2'

networks:
  integration-test-example:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
      PORT: 2565
    volumes:
      - $PWD:/go/src/target
    depends_on: 
      - db
    networks:
      - integration-test-example
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-example
    